### ISSUE TITLE
Upgrade Hoxton SR1 and Boot 2.2.4

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-build#6]

**Comment by ilayaperumalg** [comment]
Hoxton.SR1 would bring Spring Boot 2.2.2.RELEASE. I guess we are ok with that?

**Comment by jvalkeal** [comment]
We can go even further as we can now bump boot to 2.2.4. It's a good time to test these cases where we want to use newer boot version.

**Comment by jvalkeal** [comment]
Think we need to start removing cloud versions from dataflow/skipper as these are now coming from build.
