### ISSUE TITLE
Update boot 2.7.0-RC1

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-build#73]

**Comment by onobc** [comment]
Are we planning on bumping to 2.7? I don't think we need to.

**Comment by onobc** [comment]
We are bumping to 2.7 to more cleanly support the MySQL/MariaDB snafu as well as stay on the latest SB 2.x line.

**Comment by onobc** [comment]
Be sure to bump SCT to latest (2.4?) to pickup some H2 fixes.
