### ISSUE TITLE
Add checkstyle to build tools

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-build#9]
We didn't take spring-cloud-build-tools concept for our dataflow build and that's required for checkstyle(it would come from classpath) if we want to have a common one and not hardcode config location(needed to run builds from module directories).

**Comment by ilayaperumalg** [comment]
Will this enforce checkstyle validation for all the projects that use `spring-cloud-dataflow-build` as parent?

**Comment by jvalkeal** [comment]
Currently it would not as build only does plugin configuration via management sections. It's been same in `spring-cloud-build` as well where project needs to enable checkstyle. We could enable it for all if we want to.
